#ifndef DS4_QWEN4_TQ_H
#define DS4_QWEN4_TQ_H

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TurboQuant (TQ-MSE) KV codec for the Qwen3.8-Flash-Next attention caches.
 *
 * Data-oblivious codec: everything derives from (dim=256, bits, seed=0),
 * matching mlx-vlm's turboquant.py (_TurboQuantMSECodec) bit-for-bit:
 * an exact f16 row norm + the RHT-rotated unit vector quantized against a
 * fixed beta-PDF Lloyd codebook, packed LSB-first into u32 words.
 * Every integer width DS4_QWEN4_TQ_MIN_BITS..DS4_QWEN4_TQ_MAX_BITS (2..8)
 * works; 1-bit is left out on purpose (two centroids carry no usable KV
 * signal).  Tables: ds4_qwen4_tq_tables.h, generated by
 * tests/gen_qwen4_tq_tables.py (sha256 pins in
 * docs/superpowers/plans/2026-09-23-qwen4-turboquant-all-widths.md).
 *
 * Compile this translation unit WITHOUT -ffast-math: the golden vectors pin
 * exact f32 arithmetic (ascending norm accumulation, canonical butterfly). */

#define DS4_QWEN4_TQ_DIM 256u
#define DS4_QWEN4_TQ_MIN_BITS 2u
#define DS4_QWEN4_TQ_MAX_BITS 8u
/* Codebook entries of every supported width, concatenated: sum 2^b for
 * b in [MIN, MAX]. */
#define DS4_QWEN4_TQ_ENTRIES \
    ((1u << (DS4_QWEN4_TQ_MAX_BITS + 1u)) - (1u << DS4_QWEN4_TQ_MIN_BITS))
/* Width `bits` starts here in both cb[] and mid[].  mid[] holds one entry
 * fewer per width, so its last slot in the span is unused padding and both
 * tables share one base. */
#define DS4_QWEN4_TQ_TAB_BASE(bits) ((1u << (bits)) - (1u << DS4_QWEN4_TQ_MIN_BITS))

typedef struct {
    uint32_t signs[8];                        /* bit d of word w set => sign +1 */
    float cb[DS4_QWEN4_TQ_ENTRIES];           /* width b: cb[base(b) + 0 .. +2^b) */
    float mid[DS4_QWEN4_TQ_ENTRIES];          /* width b: base(b) + 0 .. +2^b-2 */
} ds4_qwen4_tq_tables;                        /* 4096 bytes; GPU-uploaded verbatim */

extern const ds4_qwen4_tq_tables ds4_qwen4_tq_table;

/* Widths this build has codebooks for; anything else must stay on f16 KV. */
bool ds4_qwen4_tq_bits_supported(uint32_t bits);
/* Per-width views of the concatenated tables (centroids, midpoints). */
const float *ds4_qwen4_tq_cb(uint32_t bits);
const float *ds4_qwen4_tq_mid(uint32_t bits);

/* Packed-code words per (token, kv head) row: bits*8 (16 at 2 bits .. 64 at 8).
 * 256 dims x bits always fills whole words, so a 32-dim span is exactly
 * `bits` words and its codes never reach past them. */
uint32_t ds4_qwen4_tq_packed_width(uint32_t bits);
/* Byte offset of the f16 norms inside a blob (codes first, 16-aligned). */
uint64_t ds4_qwen4_tq_norms_offset(uint64_t cap, uint32_t bits);
/* Whole blob: codes [cap][2][pw] u32 + norms [cap][2] f16 (Hkv=2 fixed). */
uint64_t ds4_qwen4_tq_blob_bytes(uint64_t cap, uint32_t bits);

/* Forward RHT: y = WHT(signs * x) / 16.  Canonical butterfly: stages
 * ascending, stride 2^s pairs (i, i+2^s) -> (a+b, a-b); the /16 is exact.
 * In-place (x == y) is safe. */
void ds4_qwen4_tq_rht(const float *x, float *y);
/* Inverse RHT: x = signs * (WHT(y) / 16).  In-place is safe. */
void ds4_qwen4_tq_rht_inverse(const float *y, float *x);

/* row: 256 f32 values (one (token, kv head) K or V row).  codes: pw words.
 * norm_f16: round-to-nearest-even f16 bits of the f32 row norm. */
void ds4_qwen4_tq_quantize_row(const float *row, uint32_t bits,
                               uint32_t *codes, uint16_t *norm_f16);
/* Reconstructs norm * RHT^-1(codebook[codes]) into row (256 f32). */
void ds4_qwen4_tq_dequantize_row(const uint32_t *codes, uint16_t norm_f16,
                                 uint32_t bits, float *row);

/* Layer policy (mirrors oMLX should_quantize_kv_layer): among the trunk
 * attention layers ((il+1) % attn_interval == 0, il < n_layer - n_nextn),
 * deep stacks (> 2 attention layers) keep the LAST one in f16 — it is
 * quantization-sensitive; shallow stacks quantize every attention layer.
 * nextn/MTP blocks and linear (GDN) layers are never quantized. */
bool ds4_qwen4_tq_layer_want(uint32_t il, uint32_t n_layer, uint32_t n_nextn,
                             uint32_t attn_interval);

#ifdef __cplusplus
}
#endif

#endif /* DS4_QWEN4_TQ_H */
